### ISSUE TITLE
Required validator not working for NaN

### ISSUE THREAD

**Issue by DCosti** [osstotalsoft/jsbb#24]
When using the "useValidation" hook for validating model with a property that is NaN using required as validator, the validation passes.

**Comment by oncicaradupopovici** [comment]
Indeed primitive required field validator does not take NaN into account.
Maybe it should.
export const required = Validator(function required(x) {
  return x !== null && x !== undefined && (typeof x === "string" ? x !== "" : true)
    ? Success
    : Failure(ValidationError(translate("Validations.Generic.Mandatory")));
})

**Comment by fraliv13** [comment]
The "required" validator will not treat NaN as a missing value, but we added two new primitive validators "integer" and "number". For this use case you can use:
```javascript
[required, number] |> stopOnFirstFailure
```
or
```javascript
[required, integer] |> stopOnFirstFailure
```
