### ISSUE TITLE
Pipeline Operator Not translated well in node_module

### ISSUE THREAD

**Issue by dragos-rosca** [osstotalsoft/jsbb#44]
https://github.com/osstotalsoft/jsbb/blob/7fddf81373849832a1d996692adccae6a8089c44/packages/react-state-lens/src/hooks/useStateLens.js#L8

When I use "useStateLens" I get "Object is not a function" error.
From debugging I see that `return StateLens(state, setState) |> LensProxy` is transformed into `return StateLens(state, setState), LensProxy`

**Comment by fraliv13** [comment]
The error was caused by incorrect usage due to a mistake in the documentation. The hook returns a lens not an array:
```javascript
const lens = useStateLens({ a: "test"})
```
I updated the docuementation with the correct usage.

Babel translates the pipeline operator by multiple assignments on the same line using comma operator

```javascript
return _StateLens = StateLens(state, setState), LensProxy(_StateLens);
```

which is equivalent to:
```javascript
_StateLens = StateLens(state, setState)
return LensProxy(_StateLens);
```
